In [2]:
import numpy as np

x = np.array([[1, 2, 3],
              [4, 5, 6]])
print(type(x))
print(x)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

x = np.arange(8).reshape(4, 2)
print(x)
print(x.transpose())

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 2 4 6]
 [1 3 5 7]]


In [4]:
import numpy as np

x = np.array([[1, 0, 2],
              [-1, 3, 1]])
y = np.array([[3, 1],
              [2, 1],
              [1, 0]])
z = x @ y
print(z)

[[5 1]
 [4 2]]


In [7]:
import numpy as np

A = np.matrix([[2, 3],
               [5, 7]])
A_inv = np.linalg.inv(A)

print('A_inv = {}'.format(A_inv))
print('E     = {}'.format((A * A_inv).astype(np.int64)))

A_inv = [[-7.  3.]
 [ 5. -2.]]
E     = [[1 0]
 [0 0]]


In [9]:
import numpy as np

X  = np.array([[1, 1],
               [1, 2],
               [1, 3]])
XT  = X.transpose()
XTX = XT @ X
XTX_inv = np.linalg.inv(XTX)
y = np.array([[5],
              [10],
              [20]])
B = XTX_inv @ XT @ y
print(f'a = {B[1][0]}')
print(f'b = {B[0][0]}')

a = 7.5
b = -3.333333333333343
